title: Your Site Title
description: >- # this means to ignore newlines until "baseurl:"
  This is your site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chadvanderbilt.github.io/methylation_projections" # the base hostname & protocol for your site
theme: minima # you can choose a different theme if you like

